### ISSUE TITLE
Automated pdf from latex

### ISSUE THREAD

**Issue by jellis18** [kristina-islo/OS-tests-analysis#2]
As usual, good old DFM already has a [blog](http://dan.iel.fm/posts/travis-latex/) post on this! @kristina-islo since you have the permissions can you try to set this up?

**Comment by kristina-islo** [comment]
Yep.

**Comment by jellis18** [comment]
Actually some of this seems over complicated. I would just follow the instructions for how to set up travis with your Github key. For the `.travis.yml` file I would use something like [this](https://github.com/jellis18/cv/blob/master/.travis.yml) since we already have a Makefile, that way you don't have to have the `.ci/build-paper.sh` script.

**Comment by jellis18** [comment]
I think I have this setup up but we need the GITHUB_API_KEY. @kristina-islo, can you go [here](https://github.com/settings/tokens) and make a token named `GITHUB_API_KEY` and then go [here](https://travis-ci.org/kristina-islo/OS-tests-analysis/settings) and set it as an environment variable?
